

# UI Requirements Analysis Tasks
list_pages_task:
  description: >
    this is a summary for the project {meeting_summary}
    this is the requirements for the project {requirements}
    Analyze the application and create a comprehensive list of all pages:
    - Page name/title
    - Brief description of the page's purpose
    - Any special characteristics or features
    - Navigation relationships
    - User flow context
  expected_output: >
    A detailed list of all pages including:
    - Page names and titles
    - Purpose descriptions
    - Special features
    - Navigation context
  agent: page_listing_agent

analyze_components_task:
  description: >
    For each page identified, analyze and list all UI components:
    - Component type/name
    - Purpose/functionality
    - Key properties or characteristics
    - Any special behaviors or interactions
    - Component states and variations
  expected_output: >
    A comprehensive component analysis including:
    - Component inventory
    - Purpose descriptions
    - Property specifications
    - Behavior documentation
  agent: component_analysis_agent

analyze_hierarchy_task:
  description: >
    For each page, analyze and document the view hierarchy:
    - Element name/type
    - Parent element
    - Child elements (if any)
    - Position in the hierarchy
    - Layout constraints or relationships
    return only the hierarchy with no other text.
  expected_output: >
    Detailed view hierarchy documentation including:
    - Element relationships
    - Hierarchy structure
    - Layout constraints
    - Position specifications
    make sure to return all the hierarchy of each page.
  agent: hierarchy_analysis_agent
  
summary_task:
  description: >
    summarize each page in the hierarchy in one paragraph represents the details of the page.
    each page should be in one paragraph.
    split each paragraph with a new line.
    i need it just text not a markdown file.
  expected_output: >
    summary paragraph
  agent: summarizer