# UI Components Analysis Tasks
page_structure_task:
  description: >
    Define the basic structure and layout of each page:
    - Main sections and containers
    - Layout grid system
    - Content areas
    - Spacing and margins
    - Responsive breakpoints
  expected_output: >
    A detailed page structure specification including:
    - Section definitions
    - Container layouts
    - Grid system
    - Spacing rules
  agent: page_structure_agent

component_identification_task:
  description: >
    Identify all UI components for each page:
    - Component types (buttons, forms, tables, etc.)
    - Component purposes
    - Component states
    - Component variations
  expected_output: >
    A comprehensive list of UI components including:
    - Component inventory
    - Component purposes
    - Component states
    - Component variations
  agent: component_identification_agent

component_positioning_task:
  description: >
    Define precise component positioning:
    - Exact coordinates or grid positions
    - Component dimensions
    - Spacing between components
    - Alignment rules
    - Responsive behavior
  expected_output: >
    Detailed component positioning specifications including:
    - Position coordinates
    - Size dimensions
    - Spacing values
    - Alignment rules
  agent: component_positioning_agent

component_relationship_task:
  description: >
    Define component relationships:
    - Parent-child relationships
    - Component dependencies
    - Interaction flows
    - Data relationships
  expected_output: >
    Component relationship specifications including:
    - Hierarchy diagrams
    - Dependency maps
    - Interaction flows
    - Data connections
  agent: component_relationship_agent

visual_hierarchy_task:
  description: >
    Define visual hierarchy:
    - Component importance levels
    - Size relationships
    - Emphasis rules
    - Visual flow
  expected_output: >
    Visual hierarchy specifications including:
    - Importance levels
    - Size relationships
    - Emphasis rules
    - Visual flow patterns
  agent: visual_hierarchy_agent
  